### PR TITLE
Add support to make_deb.py to work also for JRE instead of JDK

### PR DESCRIPTION
**Pull request by chalstrick**

### CODE REVIEW

**Review by MBaesken — COMMENTED** [review]
jre/control 
Should'nt this be something else than JDK line lines 29+30 ?  Looks like a copy error ?

jre/install
/usr/lib/jvm/sapmachine-${major}   
Not sure, this might clash with a JDk install  - probably we need here -jre or something like this in the name?

**Comment by chalstrick** [comment]
@MBaesken : Both of your comments point to flaws in my initial request. I fixed it and pushed a new version

**Comment by MBaesken** [comment]
debian-templates/jre/control

Provides
java-compiler
makes probably no sense for jre , I think there is no compiler (javac) in JRE.
Should we handle jre-11 too in the provides flags ?


debian-templates/jre/postinst

the
`update-alternatives --install /usr/bin/$$i $$i /usr/lib/jvm/sapmachine-${major}/bin/$$i`
path does not match any more the  path in install file

**Comment by RealCLanger** [comment]
Maybe you want to modify make_deb.py right away, instead of adding a make_deb_ext.py?

**Comment by chalstrick** [comment]
spent some time to find out ... this commit is already in origin/master. So I will close this one

**Pull request closed without merging**
